name: Release & Publish to npm

on:
  release:
    types: [published]

jobs:
  publish-azurajs:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, '-azurajs')

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: package/azurajs
        run: bun install

      - name: Build
        working-directory: package/azurajs
        run: bun run build

      - name: Publish azurajs
        working-directory: package/azurajs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-cdn:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, '-cdn')

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: package/cdn
        run: bun install

      - name: Build
        working-directory: package/cdn
        run: bun run build

      - name: Publish cdn
        working-directory: package/cdn
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
